version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib
      - npm run cy:parallel
  post_build:
    commands:
      - aws s3 sync allure-report s3://test-report-cypress/
      - aws s3 cp --recursive --acl public-read s3://test-report-cypress/ s3://test-report-cypress/ --metadata-directive REPLACE
      - echo "The report can be found here <https://test-report-cypress.s3.eu-west-3.amazonaws.com/index.html>"